Vagrant.configure("2") do |c|
  c.vm.box = "opscode-ubuntu-12.04"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-12.04_chef-provisionerless.box"
  c.vm.hostname = "default-ubuntu-1204.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>8980, :host=>8980, :auto_correct=>true})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :vmware_fusion do |p|
    p.vmx["cpus"] = "2"
    p.vmx["memsize"] = "2048"
  end
end
